const locations = [
  {
    name: 'Pekayon Jaya',
    href: 'bengkel-las-pekayon-jaya',
    slug: 'pekayon',
    lat: -6.224221,
    lng: 106.88475,
    additionalInfo: true,
    subtitle: 'Jasa Las Profesional untuk Wilayah Pekayon Jaya Bekasi',
    description: 'Bengkel Las Pekayon Jaya',
    img: '/2.png'
  },
  {
    name: 'Pondok Gede',
    href: 'bengkel-las-pondok-gede',
    slug: 'pondok gede',
    lat: -6.29517,
    lng: 107.079179,
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Pondok Gede',
    description: 'Bengkel Las Pondok Gede',
    img: '/3.png'
  },
  {
    name: 'Galaxy Bekasi',
    href: 'bengkel-las-galaxy-bekasi',
    slug: 'Galaxy Bekasi',
    lat: -6.3648,
    lng: 106.892929,
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Galaxy Bekasi',
    description: 'Bengkel Las Galaxy Bekasi. ',
    img: '/4.png'
  },
  {
    name: 'Tambun Selatan',
    href: 'bengkel-las-tambun-selatan',
    slug: 'Tambun Selatan',
    lat: -6.425758,
    lng: 106.959122,
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Tambun Selatan',
    description: 'Bengkel Las Tambun Selatan.',
    img: '/5.png'
  },
  {
    name: 'Harapan Indah',
    href: 'bengkel-las-harapan-indah',
    slug: 'bekasi',
    lat: -6.261894,
    lng: 106.977853,
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Harapan Indah',
    description: 'Bengkel Las Harapan Indah',
    img: '/1.png'
  },
  {
    name: 'Bintara',
    href: 'bengkel-las-bintara',
    slug: 'bintara',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Bintara',
    description: 'Bengkel Las Bintara',
    img: ''
  },
  {
    name: 'Bintara Jaya',
    href: 'bengkel-las-bintara-jaya',
    slug: 'bintara-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Bintara Jaya',
    description: 'Bengkel Las Bintara Jaya',
    img: ''
  },
  {
    name: 'Kranji',
    href: 'bengkel-las-kranji',
    slug: 'kranji',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Kranji',
    description: 'Bengkel Las Kranji',
    img: ''
  },
  {
    name: 'Jakasampurna',
    href: 'bengkel-las-jakasampurna',
    slug: 'jakasampurna',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Jakasampurna',
    description: 'Bengkel Las Jakasampurna',
    img: ''
  },
  {
    name: 'Kota Baru',
    href: 'bengkel-las-kota-baru',
    slug: 'kota-baru',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Kota Baru',
    description: 'Bengkel Las Kota Baru',
    img: ''
  },
  {
    name: 'Jakamulya',
    href: 'bengkel-las-jakamulya',
    slug: 'jakamulya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Jakamulya',
    description: 'Bengkel Las Jakamulya',
    img: ''
  },
  {
    name: 'Jakasetia',
    href: 'bengkel-las-jakasetia',
    slug: 'jakasetia',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Jakasetia',
    description: 'Bengkel Las Jakasetia',
    img: ''
  },
  {
    name: 'Kayuringin Jaya',
    href: 'bengkel-las-kayuringin-jaya',
    slug: 'kayuringin-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Kayuringin Jaya',
    description: 'Bengkel Las Kayuringin Jaya',
    img: ''
  },
  {
    name: 'Marga Jaya',
    href: 'bengkel-las-marga-jaya',
    slug: 'marga-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Marga Jaya',
    description: 'Bengkel Las Marga Jaya',
    img: ''
  },
  {
    name: 'Pekayon Jaya',
    href: 'bengkel-las-pekayon-jaya',
    slug: 'pekayon-jaya',
    lat: -6.224221,
    lng: 106.88475,
    additionalInfo: true,
    subtitle: 'Jasa Las Profesional untuk Wilayah Pekayon Jaya Bekasi',
    description: 'Bengkel Las Pekayon Jaya',
    img: ''
  },
  {
    name: 'Aren Jaya',
    href: 'bengkel-las-aren-jaya',
    slug: 'aren-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Aren Jaya',
    description: 'Bengkel Las Aren Jaya',
    img: ''
  },
  {
    name: 'Bekasi Jaya',
    href: 'bengkel-las-bekasi-jaya',
    slug: 'bekasi-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Bekasi Jaya',
    description: 'Bengkel Las Bekasi Jaya',
    img: ''
  },
  {
    name: 'Duren Jaya',
    href: 'bengkel-las-duren-jaya',
    slug: 'duren-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Duren Jaya',
    description: 'Bengkel Las Duren Jaya',
    img: ''
  },
  {
    name: 'Margahayu',
    href: 'bengkel-las-margahayu',
    slug: 'margahayu',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Margahayu',
    description: 'Bengkel Las Margahayu',
    img: ''
  },
  {
    name: 'Harapan Baru',
    href: 'bengkel-las-harapan-baru',
    slug: 'harapan-baru',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Harapan Baru',
    description: 'Bengkel Las Harapan Baru',
    img: ''
  },
  {
    name: 'Harapan Jaya',
    href: 'bengkel-las-harapan-jaya',
    slug: 'harapan-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Harapan Jaya',
    description: 'Bengkel Las Harapan Jaya',
    img: ''
  },
  {
    name: 'Kaliabang Tengah',
    href: 'bengkel-las-kaliabang-tengah',
    slug: 'kaliabang-tengah',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Kaliabang Tengah',
    description: 'Bengkel Las Kaliabang Tengah',
    img: ''
  },
  {
    name: 'Marga Mulya',
    href: 'bengkel-las-marga-mulya',
    slug: 'marga-mulya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Marga Mulya',
    description: 'Bengkel Las Marga Mulya',
    img: ''
  },
  {
    name: 'Teluk Pucung',
    href: 'bengkel-las-teluk-pucung',
    slug: 'teluk-pucung',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Teluk Pucung',
    description: 'Bengkel Las Teluk Pucung',
    img: ''
  },
  {
    name: 'Harapan Mulya',
    href: 'bengkel-las-harapan-mulya',
    slug: 'harapan-mulya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Harapan Mulya',
    description: 'Bengkel Las Harapan Mulya',
    img: ''
  },
  {
    name: 'Kalibaru',
    href: 'bengkel-las-kalibaru',
    slug: 'kalibaru',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Kalibaru',
    description: 'Bengkel Las Kalibaru',
    img: ''
  },
  {
    name: 'Medan Satria',
    href: 'bengkel-las-medan-satria',
    slug: 'medan-satria',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Medan Satria',
    description: 'Bengkel Las Medan Satria',
    img: ''
  },
  {
    name: 'Pejuang',
    href: 'bengkel-las-pejuang',
    slug: 'pejuang',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Pejuang',
    description: 'Bengkel Las Pejuang',
    img: ''
  },
  {
    name: 'Cimuning',
    href: 'bengkel-las-cimuning',
    slug: 'cimuning',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Cimuning',
    description: 'Bengkel Las Cimuning',
    img: ''
  },
  {
    name: 'Mustika Jaya',
    href: 'bengkel-las-mustika-jaya',
    slug: 'mustika-jaya',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Mustika Jaya',
    description: 'Bengkel Las Mustika Jaya',
    img: ''
  },
  {
    name: 'Mustika Sari',
    href: 'bengkel-las-mustika-sari',
    slug: 'mustika-sari',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Mustika Sari',
    description: 'Bengkel Las Mustika Sari',
    img: ''
  },
  {
    name: 'Padurenan',
    href: 'bengkel-las-padurenan',
    slug: 'padurenan',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Padurenan',
    description: 'Bengkel Las Padurenan',
    img: ''
  },
  {
    name: 'Jati Bening',
    href: 'bengkel-las-jati-bening',
    slug: 'jati-bening',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Jati Bening',
    description: 'Bengkel Las Jati Bening',
    img: ''
  },
  {
    name: 'Jati Bening Baru',
    href: 'bengkel-las-jati-bening-baru',
    slug: 'jati-bening-baru',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Jati Bening Baru',
    description: 'Bengkel Las Jati Bening Baru',
    img: ''
  },
  {
    name: 'Jati Cempaka',
    href: 'bengkel-las-jati-cempaka',
    slug: 'jati-cempaka',
    lat: '',
    lng: '',
    additionalInfo: false,
    subtitle: 'Jasa Las Profesional untuk Wilayah Jati Cempaka',
    description: 'Bengkel Las Jati Cempaka',
    img: ''
  }
]

export default locations
